import re
from io import StringIO
import tempfile
import subprocess
import os

def perl_preproc(inputfile):
    data =  open(inputfile).read()

    # escape escaped quotes, quotes and @
    data = re.sub(r'\\"', r'\\\\\\"', data)
    data = re.sub(r'([^\\])"', r'\1\\"', data)
    data = re.sub(r'@', r'\\@', data)
    # process perl snippets
    # if <%=VAR%>, close quote, print VAR, print open quote
    data = re.sub(r'<%=(\$.+?)%>', r'"; print $fh \1; print $fh "', data)
    # if <%, close quote
    data = re.sub(r'<%', r'"; ', data)
    # if %>, print open quote
    data = re.sub(r'%>', r'print $fh "', data)
    # print line number to temp file
    data = re.sub(r'^', r'"; print $fhl __LINE__, "\\n";  print $fh "', data, flags=re.MULTILINE)
    # enclose in perl print
    data = 'print $fh "' + data + '";';

    # perl file
    fpl = tempfile.NamedTemporaryFile(mode='w', delete=False)
    fpl.write(data)
    fpl.close()
    # perl processed file
    fpp = tempfile.NamedTemporaryFile(delete=False)
    fpp.close()
    # line number file generated by perl file
    fln = tempfile.NamedTemporaryFile(delete=False)
    fln.close()

    process = subprocess.Popen(['perl', 'parser/preproc.pl', fpl.name, fpp.name, fln.name],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = process.communicate()
    out = out.decode('utf-8')
    
    os.remove(fpl.name)
    pp = open(fpp.name).read()
    os.remove(fpp.name)
    ln = [int(i) for i in open(fln.name).readlines()]
    os.remove(fln.name)

    if out:
        # todo: set proper output messages
        # multi line perl snippet not allowed (close <% on same line)
        print(out)
        exit()
    return (pp, ln)
